apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      image: registry.lab.dynatrace.org/jci/ubuntu20-amd64-base:latest
      imagePullPolicy: Always
      args:
        - "jenkins-slave"
      resources:
        requests:
          cpu: "250m" 
          memory: "512Mi"
